### Typescript Webpack starter

[[projects]]
names = ["rust-wasm-web"]
description = "A rust wasm starter project bundled with vite"

[[projects.commands]]
type = "command"
command = "yarn"
args =  ["create", "vite", ".", "--template", "vanilla-ts"]

[[projects.commands]]
type = "command"
command = "yarn"
args =  []


[[projects.commands]]
type = "command"
command = "yarn"
args =  ["add", "-D", "vite", "vite-plugin-wasm-pack"]

[[projects.commands]]
type = "command"
command = "cargo"
args =  ["init", "--lib", "innards"]


[[projects.commands]]
type = "create"
file = "Cargo.toml"
contents = """ \
[workspace]
members = ["innards"]
"""

[[projects.commands]]
type = "copy"
src_file = "rust-wasm-web/vite.config.ts"
dest_file = "vite.config.ts"

[[projects.commands]]
type = "copy"
src_file = "rust-wasm-web/main.ts"
dest_file = "src/main.ts"

[[projects.commands]]
type = "copy"
src_file = "rust-wasm-web/lib.rs"
dest_file = "innards/src/lib.rs"

[[projects.commands]]
type = "append"
file = "innards/Cargo.toml"
contents = """

[lib]
crate-type = ["cdylib"]
"""

[[projects.commands]]
type = "append"
file = ".gitignore"
contents = """

target
"""

[[projects.commands]]
type = "remove"
file = "public/vite.svg"

[[projects.commands]]
type = "remove"
file = "src/typescript.svg"

[[projects.commands]]
type = "remove"
file = "src/counter.ts"

[[projects.commands]]
type = "template"
template = "package.json"
dest_file = "package.json"
[projects.commands.replacements]
main = ""
type = "module"
scripts = """
        "dev": "wasm-pack build ./innards --target web && yarn build && tsc && yarn preview",
        "build": "vite build",
        "preview": "vite preview"
"""

[[projects.commands]]
type = "multicommand"
command = """cd innards \
        && cargo add wasm-bindgen \
        && cargo add console_error_panic_hook \
"""

[[projects.commands]]
type = "command"
command = "yarn"
args =  ["add", "-D", "vite-plugin-wasm-pack", "typescript", "vite" ]

[[projects.commands]]
type = "command"
command = "wasm-pack"
args =  ["build", "./innards", "--target", "web"]

